// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaVoto.API.Data;

#nullable disable

namespace SistemaVoto.API.Migrations
{
    [DbContext(typeof(VotacionDbContext))]
    [Migration("20260215172047_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Models.Candidato", b =>
                {
                    b.Property<int>("CandidatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CandidatoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ListaPoliticaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Propuestas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CandidatoId");

                    b.HasIndex("EleccionId");

                    b.HasIndex("ListaPoliticaId");

                    b.HasIndex("Cedula", "EleccionId")
                        .IsUnique();

                    b.ToTable("Candidatos", (string)null);
                });

            modelBuilder.Entity("Models.Models.CertificadoVotacion", b =>
                {
                    b.Property<int>("CertificadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CertificadoId"));

                    b.Property<int>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroConfirmacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VotanteId")
                        .HasColumnType("integer");

                    b.HasKey("CertificadoId");

                    b.HasIndex("EleccionId");

                    b.HasIndex("NumeroConfirmacion")
                        .IsUnique();

                    b.HasIndex("VotanteId", "EleccionId")
                        .IsUnique();

                    b.ToTable("CertificadosVotacion", (string)null);
                });

            modelBuilder.Entity("Models.Models.CodigoVoto", b =>
                {
                    b.Property<int>("CodigoVotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodigoVotoId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaUso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("JefeDeJuntaId")
                        .HasColumnType("integer");

                    b.Property<int>("VotanteId")
                        .HasColumnType("integer");

                    b.HasKey("CodigoVotoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EleccionId");

                    b.HasIndex("JefeDeJuntaId");

                    b.HasIndex("VotanteId", "EleccionId")
                        .IsUnique();

                    b.ToTable("CodigosVoto", (string)null);
                });

            modelBuilder.Entity("Models.Models.Eleccion", b =>
                {
                    b.Property<int>("EleccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EleccionId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("ResultadosPublicos")
                        .HasColumnType("boolean");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("EleccionId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaInicio");

                    b.ToTable("Elecciones", (string)null);
                });

            modelBuilder.Entity("Models.Models.Incidencia", b =>
                {
                    b.Property<int>("IncidenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncidenciaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JefeDeJuntaId")
                        .HasColumnType("integer");

                    b.Property<string>("Resolucion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("VotanteId")
                        .HasColumnType("integer");

                    b.HasKey("IncidenciaId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaReporte");

                    b.HasIndex("JefeDeJuntaId");

                    b.HasIndex("VotanteId");

                    b.ToTable("Incidencias", (string)null);
                });

            modelBuilder.Entity("Models.Models.JefeDeJunta", b =>
                {
                    b.Property<int>("JefeDeJuntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JefeDeJuntaId"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UbicacionAsignadaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("JefeDeJuntaId");

                    b.HasIndex("UbicacionAsignadaId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("JefesDeJunta", (string)null);
                });

            modelBuilder.Entity("Models.Models.ListaPolitica", b =>
                {
                    b.Property<int>("ListaPoliticaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ListaPoliticaId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ListaPoliticaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ListasPoliticas", (string)null);
                });

            modelBuilder.Entity("Models.Models.LogActividad", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DatosAdicionales")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DireccionIP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("LogId");

                    b.HasIndex("Accion");

                    b.HasIndex("Fecha");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsActividad", (string)null);
                });

            modelBuilder.Entity("Models.Models.UbicacionVotacion", b =>
                {
                    b.Property<int>("UbicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UbicacionId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CapacidadVotantes")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroMesa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("UbicacionId");

                    b.HasIndex("Nombre", "NumeroMesa");

                    b.ToTable("UbicacionesVotacion", (string)null);

                    b.HasData(
                        new
                        {
                            UbicacionId = 1,
                            Activo = true,
                            CapacidadVotantes = 300,
                            Direccion = "Av. Principal 123",
                            Nombre = "Escuela Central",
                            NumeroMesa = "001"
                        },
                        new
                        {
                            UbicacionId = 2,
                            Activo = true,
                            CapacidadVotantes = 250,
                            Direccion = "Calle Norte 456",
                            Nombre = "Colegio Norte",
                            NumeroMesa = "002"
                        });
                });

            modelBuilder.Entity("Models.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("TokenExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenVerificacion")
                        .HasColumnType("text");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Apellido = "Sistema",
                            Cedula = "0000000000",
                            Email = "admin@votacion.com",
                            Estado = "Activa",
                            FechaCreacion = new DateTime(2026, 2, 15, 17, 20, 46, 200, DateTimeKind.Utc).AddTicks(4176),
                            FechaVerificacion = new DateTime(2026, 2, 15, 17, 20, 46, 200, DateTimeKind.Utc).AddTicks(4184),
                            Nombre = "Admin",
                            PasswordHash = "$2a$11$dgz2Sy4YkMYdjRphomc4jeZ.aF107AUwLa/0po621ns9hPIO6ILWy",
                            Rol = "Administrador"
                        });
                });

            modelBuilder.Entity("Models.Models.Votante", b =>
                {
                    b.Property<int>("VotanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VotanteId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("FechaPresenciaRecinto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UbicacionAsignadaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("VotanteId");

                    b.HasIndex("UbicacionAsignadaId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Votantes", (string)null);
                });

            modelBuilder.Entity("Models.Models.Voto", b =>
                {
                    b.Property<int>("VotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VotoId"));

                    b.Property<int>("CandidatoId")
                        .HasColumnType("integer");

                    b.Property<int>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VotanteId")
                        .HasColumnType("integer");

                    b.Property<string>("VotoEncriptado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VotoId");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("EleccionId");

                    b.HasIndex("FechaEmision");

                    b.HasIndex("VotanteId", "EleccionId")
                        .IsUnique();

                    b.ToTable("Votos", (string)null);
                });

            modelBuilder.Entity("Models.Models.Candidato", b =>
                {
                    b.HasOne("Models.Models.Eleccion", "Eleccion")
                        .WithMany("Candidatos")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Models.ListaPolitica", "ListaPolitica")
                        .WithMany("Candidatos")
                        .HasForeignKey("ListaPoliticaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Eleccion");

                    b.Navigation("ListaPolitica");
                });

            modelBuilder.Entity("Models.Models.CertificadoVotacion", b =>
                {
                    b.HasOne("Models.Models.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Models.Votante", "Votante")
                        .WithMany("Certificados")
                        .HasForeignKey("VotanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleccion");

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("Models.Models.CodigoVoto", b =>
                {
                    b.HasOne("Models.Models.Eleccion", "Eleccion")
                        .WithMany("CodigosVoto")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Models.JefeDeJunta", "JefeDeJunta")
                        .WithMany("CodigosGenerados")
                        .HasForeignKey("JefeDeJuntaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Models.Votante", "Votante")
                        .WithMany("CodigosVoto")
                        .HasForeignKey("VotanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleccion");

                    b.Navigation("JefeDeJunta");

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("Models.Models.Incidencia", b =>
                {
                    b.HasOne("Models.Models.JefeDeJunta", "JefeDeJunta")
                        .WithMany("IncidenciasReportadas")
                        .HasForeignKey("JefeDeJuntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Models.Votante", "Votante")
                        .WithMany()
                        .HasForeignKey("VotanteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("JefeDeJunta");

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("Models.Models.JefeDeJunta", b =>
                {
                    b.HasOne("Models.Models.UbicacionVotacion", "UbicacionAsignada")
                        .WithMany("JefesAsignados")
                        .HasForeignKey("UbicacionAsignadaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Models.Usuario", "Usuario")
                        .WithOne("JefeDeJunta")
                        .HasForeignKey("Models.Models.JefeDeJunta", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UbicacionAsignada");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Models.Models.LogActividad", b =>
                {
                    b.HasOne("Models.Models.Usuario", "Usuario")
                        .WithMany("LogsActividad")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Models.Models.Votante", b =>
                {
                    b.HasOne("Models.Models.UbicacionVotacion", "UbicacionAsignada")
                        .WithMany("VotantesAsignados")
                        .HasForeignKey("UbicacionAsignadaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Models.Usuario", "Usuario")
                        .WithOne("Votante")
                        .HasForeignKey("Models.Models.Votante", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UbicacionAsignada");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Models.Models.Voto", b =>
                {
                    b.HasOne("Models.Models.Candidato", "Candidato")
                        .WithMany("Votos")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Models.Eleccion", "Eleccion")
                        .WithMany("Votos")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Models.Votante", "Votante")
                        .WithMany("Votos")
                        .HasForeignKey("VotanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Eleccion");

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("Models.Models.Candidato", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Models.Models.Eleccion", b =>
                {
                    b.Navigation("Candidatos");

                    b.Navigation("CodigosVoto");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Models.Models.JefeDeJunta", b =>
                {
                    b.Navigation("CodigosGenerados");

                    b.Navigation("IncidenciasReportadas");
                });

            modelBuilder.Entity("Models.Models.ListaPolitica", b =>
                {
                    b.Navigation("Candidatos");
                });

            modelBuilder.Entity("Models.Models.UbicacionVotacion", b =>
                {
                    b.Navigation("JefesAsignados");

                    b.Navigation("VotantesAsignados");
                });

            modelBuilder.Entity("Models.Models.Usuario", b =>
                {
                    b.Navigation("JefeDeJunta")
                        .IsRequired();

                    b.Navigation("LogsActividad");

                    b.Navigation("Votante")
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Models.Votante", b =>
                {
                    b.Navigation("Certificados");

                    b.Navigation("CodigosVoto");

                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
